vs 2015/MVCDemos/MVCDemos/Controllers/AngularJsDemosController.cs
using MVCDemos.Models;
using MVCDemos.Repositories;
using NHibernate;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace MVCDemos.Controllers
{
    public class AngularJsDemosController : Controller
    {
        // GET: AngularJsDemos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MultipleFileUpload()
        {
            return View();
        }

        [HttpPost]
        public virtual string UploadFiles(object obj)
        {

            var length = Request.ContentLength;
            var bytes = new byte[length];
            Request.InputStream.Read(bytes, 0, length);

            var fileName = Request.Headers["X-File-Name"];
            var fileSize = Request.Headers["X-File-Size"];
            var fileType = Request.Headers["X-File-Type"];

            var currentPath = Server.MapPath("..//AngularFileUploadImages");

            var saveToFileLoc = currentPath + "\\" + fileName;
            var fileStream = new FileStream(saveToFileLoc, FileMode.Create, FileAccess.ReadWrite);
            fileStream.Write(bytes, 0, length);
            fileStream.Close();

            return string.Format("{0} bytes uploaded", bytes.Length);
        }

        public ActionResult AngularJsDatatable()
        {
            return View();
        }
    }
}

vs 2015/MVCDemos/MVCDemos/Controllers/AutoCompleteController.cs
using MVCDemos.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCDemos.Controllers
{
    public class AutoCompleteController : Controller
    {
        public ActionResult TextBox()
        {
            return View();
        }

        [HttpPost]
        public JsonResult TextBox(string keyword)
        {
            //This can be replaced with database call.  
            List<AutoCompleteGames> objGameList = new List<AutoCompleteGames>() {
                new AutoCompleteGames {
                    Id = 1, Name = "Cricket"
                },
                new AutoCompleteGames {
                    Id = 2, Name = "Football"
                },
                new AutoCompleteGames {
                    Id = 3, Name = "Chess"
                },
                new AutoCompleteGames {
                    Id = 4, Name = "Valley Ball"
                },
                new AutoCompleteGames {
                    Id = 5, Name = "Kabbadi"
                },
                new AutoCompleteGames{
                    Id = 6, Name = "Hockey"
                }
            };
            var result = (from a in objGameList
                          where a.Name.ToLower().StartsWith(keyword.ToLower())
                          select new
                          {
                              a.Name
                          });
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

vs 2015/MVCDemos/MVCDemos/Controllers/MVCSamplesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Net.Http;

namespace MVCDemos.Controllers
{
    public class MVCSamplesController : Controller
    {
        // GET: MVCSamples
        public ActionResult Index()
        {
            return View();
        }

        private List<SelectListItem> GetCountries()
        {
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Select", Value = "0" });
            li.Add(new SelectListItem { Text = "India", Value = "1" });
            li.Add(new SelectListItem { Text = "Srilanka", Value = "2" });
            li.Add(new SelectListItem { Text = "China", Value = "3" });
            li.Add(new SelectListItem { Text = "Austrila", Value = "4" });
            li.Add(new SelectListItem { Text = "USA", Value = "5" });
            li.Add(new SelectListItem { Text = "UK", Value = "6" });

            return li;
        }
        public ActionResult CascadingDropDownDemo()
        {
            var li = GetCountries();

            ViewData["country"] = li;
            return View();
        }

        [HttpPost]
        public ActionResult CascadingDropDownDemo(FormCollection formData)
        {
            string country = Convert.ToString(formData["Country"]);
            string state = Convert.ToString(formData["State"]);
            string city = Convert.ToString(formData["City"]);


            ViewBag.CountryLabel = country;
            ViewBag.StateLabel = state;
            ViewBag.CityLabel = city;

            var li = GetCountries();

            ViewData["country"] = li;
            return View();
        }

        public JsonResult GetStates(string id)
        {
            List<SelectListItem> states = new List<SelectListItem>();
            switch (id)
            {
                case "1":
                    states.Add(new SelectListItem { Text = "Select", Value = "0" });
                    states.Add(new SelectListItem { Text = "ANDAMAN & NIKOBAR ISLANDS", Value = "1" });
                    states.Add(new SelectListItem { Text = "ANDHRA PRADESH", Value = "2" });
                    states.Add(new SelectListItem { Text = "ARUNACHAL PRADESH", Value = "3" });
                    states.Add(new SelectListItem { Text = "ASSAM", Value = "4" });
                    states.Add(new SelectListItem { Text = "BIHAR", Value = "5" });
                    states.Add(new SelectListItem { Text = "CHANDIGARH", Value = "6" });
                    states.Add(new SelectListItem { Text = "CHHATTISGARH", Value = "7" });
                    states.Add(new SelectListItem { Text = "DADRA & NAGAR HAVELI", Value = "8" });
                    states.Add(new SelectListItem { Text = "DAMAN & DIU", Value = "9" });
                    states.Add(new SelectListItem { Text = "GOA", Value = "10" });
                    states.Add(new SelectListItem { Text = "GUJARAT", Value = "11" });
                    states.Add(new SelectListItem { Text = "HARYANA", Value = "12" });
                    states.Add(new SelectListItem { Text = "HIMACHAL PRADESH", Value = "13" });
                    states.Add(new SelectListItem { Text = "JAMMU & KASHMIR", Value = "14" });
                    states.Add(new SelectListItem { Text = "JHARKHAND", Value = "15" });
                    states.Add(new SelectListItem { Text = "KARNATAKA", Value = "16" });
                    states.Add(new SelectListItem { Text = "KERALA", Value = "17" });
                    states.Add(new SelectListItem { Text = "LAKSHADWEEP", Value = "18" });
                    states.Add(new SelectListItem { Text = "MADHYA PRADESH", Value = "19" });
                    states.Add(new SelectListItem { Text = "MAHARASHTRA", Value = "20" });
                    states.Add(new SelectListItem { Text = "MANIPUR", Value = "21" });
                    states.Add(new SelectListItem { Text = "MEGHALAYA", Value = "22" });
                    states.Add(new SelectListItem { Text = "MIZORAM", Value = "23" });
                    states.Add(new SelectListItem { Text = "NAGALAND", Value = "24" });
                    states.Add(new SelectListItem { Text = "NCT OF DELHI", Value = "25" });
                    states.Add(new SelectListItem { Text = "ORISSA", Value = "26" });
                    states.Add(new SelectListItem { Text = "PUDUCHERRY", Value = "27" });
                    states.Add(new SelectListItem { Text = "PUNJAB", Value = "28" });
                    states.Add(new SelectListItem { Text = "RAJASTHAN", Value = "29" });
                    states.Add(new SelectListItem { Text = "SIKKIM", Value = "30" });
                    states.Add(new SelectListItem { Text = "TAMIL NADU", Value = "31" });
                    states.Add(new SelectListItem { Text = "TRIPURA", Value = "32" });
                    states.Add(new SelectListItem { Text = "UTTAR PRADESH", Value = "33" });
                    states.Add(new SelectListItem { Text = "UTTARAKHAND", Value = "34" });
                    states.Add(new SelectListItem { Text = "WEST BENGAL", Value = "35" });
                    break;
                case "UK":
                    break;
                case "India":
                    break;
            }
            return Json(new SelectList(states, "Value", "Text"));
        }

        public JsonResult GetCity(string id)
        {
            List<SelectListItem> City = new List<SelectListItem>();

            //switch (id)
            //{
            //    case "20":
            //    default:

            //        break;
            //}
            City.Add(new SelectListItem { Text = "Select", Value = "0" });
            City.Add(new SelectListItem { Text = "MUMBAI", Value = "1" });
            City.Add(new SelectListItem { Text = "PUNE", Value = "2" });
            City.Add(new SelectListItem { Text = "KOLHAPUR", Value = "3" });
            City.Add(new SelectListItem { Text = "RATNAGIRI", Value = "4" });
            City.Add(new SelectListItem { Text = "NAGPUR", Value = "5" });
            City.Add(new SelectListItem { Text = "JALGAON", Value = "6" });

            return Json(new SelectList(City, "Value", "Text"));
        }

        public ActionResult CKEditorSample()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CKEditorSample(FormCollection formData)
        {

            var email = Convert.ToString(formData["Email"]);
            var htmlContent = Convert.ToString(formData["Note"]);

            if (!string.IsNullOrEmpty(email))
            {
                var emailBody = htmlContent;

                var toEmail = ConfigurationManager.AppSettings["toEmail"];
                var fromEmail = ConfigurationManager.AppSettings["fromEmail"];
                var emailPassword = ConfigurationManager.AppSettings["emailPassword"];
                var emailUserName = ConfigurationManager.AppSettings["emailUserName"];

                var mail = new MailMessage();

                mail.To.Add(toEmail);
                mail.To.Add("contact@ghrana.com");

                mail.From = new MailAddress(fromEmail);
                mail.Subject = "Html Content sent from mvcdemos by gaurav rana";
                mail.Body = emailBody;
                mail.IsBodyHtml = true;

                var smtp = new SmtpClient();
                smtp.Send(mail);

                ViewBag.successMessage = "Thank you, <br/> HTML Content is sent to " + email;
            }

            return View();
        }

        [HttpGet]
        public async Task<HttpResponseMessage> GetPDFReport()
        {
            //string fileName = string.Concat("Contacts.pdf");
            //string filePath = HttpContext.Current.Server.MapPath("~/Report/" + fileName);

            //ContactController contact = new ContactController();
            //List<Contact> contacList = contact.Get().ToList();

            //await SampleEF6.Report.ReportGenerator.GeneratePDF(contacList, filePath);

            HttpResponseMessage result = null;
            //result = Request.CreateResponse(HttpStatusCode.OK);
            //result.Content = new StreamContent(new FileStream(filePath, FileMode.Open));
            //result.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
            //result.Content.Headers.ContentDisposition.FileName = fileName;

            return result;
        }

    }
}

vs 2015/MVCDemos/MVCDemos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Demos</title>
    @Styles.Render("~/Content/css")
</head>
<body>

    <header class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Demos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @*<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>*@
                    @*<li><a href="#">Link</a></li>*@

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ASP.NET MVC Demos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cascading Drop Downs", "CascadingDropDownDemo", "MVCSamples")</li>
                            <li>@Html.ActionLink("CKEditor in MVC Page", "CKEditorSample", "MVCSamples")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">JQuery Demos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Auto Complete Text Box", "Index", "AutoComplete")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="/AngularJsDemos" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Angular Demos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Multiple File Upload", "MultipleFileUpload", "AngularJsDemos")</li>
                            <li>@Html.ActionLink("AngularJs Data Table", "AngularJsDatatable", "AngularJsDemos")</li>
                        </ul>
                    </li>
                </ul>
                @*<ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>*@
            </div>
        </div>
    </header>
    <div class="container body-content ">
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom">
            <p>&copy; @DateTime.Now.Year - MVC Demos - Gaurav Rana</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>